### ISSUE TITLE
Pressing pause button will pause and then quickly resume

### ISSUE THREAD

**Issue by TheGuardianWolf** [Archmonger/Improved-Plex-Mobile#1]
During playback on my mobile device, pressing the pause button will pause playback but then resume it half a second later.

System is Android 8.0
Browser is Firefox Release

As a side note, I am inserting the js and css through userscripts I created here:
https://greasyfork.org/en/scripts/391184-plex-mobile/code

**Comment by Archmonger** [comment]
This is an issue with Plex considering a touch command as two separate presses (mouse up and mouse down), I will look into a JavaScript rate limiting as a potential fix.

**Comment by TheGuardianWolf** [comment]
Ah, was doing some further testing as you wrote that, it occurs in the unmodified version as well.

**Comment by Archmonger** [comment]
That is correct, it is native Plex behavior. A work around may be hacky, which is part of the reason I've been procrastinating on it.

**Comment by TheGuardianWolf** [comment]
This does the job for me on my laptop, I'll need to upgrade my userscript to test on mobile.

I tried to make something that would be targeted as possible to reduce side effects, feel free to adapt this to something you like.

Edit: Mobile tested, works fine, leave a message if you implement this so I can remove it from the userscript.

```javascript
document.getElementById('plex').addEventListener('touchstart', (e) => {
    let resumeButton = document.querySelectorAll('button[data-qa-id="resumeButton"]')[0];
    let pauseButton = document.querySelectorAll('button[data-qa-id="pauseButton"]')[0];

    if (
        resumeButton && resumeButton.contains(e.target) ||
        pauseButton && pauseButton.contains(e.target)
    ) {
        e.preventDefault();
    }
});
```

**Comment by Archmonger** [comment]
Very interesting implementation, I was originally thinking of going the route of global rate limiting for touch events. But this is much more localized and functional. Will add it to `plex_mobile.js`, much appreciated!
