### ISSUE TITLE
Plex spams loopback error when behind reverse proxy

### ISSUE THREAD

**Issue by mhanuszh** [Archmonger/Improved-Plex-Mobile#10]
First of all, thank you for sharing your workings with us!

While I did not see a practical impart of this, when connecting to Plex through a reverse proxy, the console is spammed with errors and warnings about unreachable loopback connection at 127.0.0.1.

```
[Connections] [Loopback] is unavailable at http://127.0.0.1:32400/media/providers (Status 0)
```

Any attempt at informing Plex about the presence of the proxy had no result.

My headers:
```
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $remote_addr;
proxy_set_header X-Forwarded-Host $remote_addr;
```

My question is, have you dealt with this problem? Do you have any advice?

**Comment by mhanuszh** [comment]
Please ignore me. I was negligent, as I did not test this without the reverse proxy. The loopback address is hardcoded, so these errors are present in every remote scenario.

Sorry for bothering you.

**Comment by Archmonger** [comment]
Yep unfortunately those errors are expected. As far as I've been able to tell, they don't affect anything.
