### ISSUE TITLE
Search bar and player controls extending past the page

### ISSUE THREAD

**Issue by TheGuardianWolf** [Archmonger/Improved-Plex-Mobile#3]
The current view from a small screen looks as follows:
![image](https://i.imgur.com/GLqcpn2.jpg)

The top controls and bottom playback controls are pushed out of the main area due to some flexbox issues(?).

**Comment by Archmonger** [comment]
Pushed some changes to the video playback controls. Unsure what you're referring to by "top controls", let me know if this fixes the issues you're referring to.

**Comment by TheGuardianWolf** [comment]
~~No, I don't think anything significant has changed~~, I'll have a go at fixing it tomorrow.

The rawgit cdn is not updating, guess I'll have to wait. In the meantime, I had a look at the changes, I think I can actually move the second row down instead of removing it entirely.

The top bar (navbar) is missing the buttons on the right side due to some flexbox issues, it gets pushed out of the screen. On my phone, this results in me being able to move the viewport out of the page. It's a very common issue for mobile designs.

I think for that I will try to shrink the search to an icon and it will expand as normal when clicked.

What's the view at your end like? It will help in writing something that works for everyone.

**Comment by Archmonger** [comment]
Mobile video player controls should now be left justified
![image](https://user-images.githubusercontent.com/16909269/66815905-f82efe80-eeed-11e9-893b-77c7d3e87099.png)

And regarding the topnav, I see this issue now. Not a flexbox issue but rather that the searchbar always is a width of 207px regardless of whether or not it's expanded. I believe I may have a fix for this.

**Comment by TheGuardianWolf** [comment]
Yeah, based on your edits I think it should be like that, I'll check tomorrow to see if the cdn refreshes. If not I'll just use stylish instead of CSS injection via JS.

**Comment by Archmonger** [comment]
Pushed some edits that fixes the overflow of navbar items on mobile displays.
Still need to dream up a solution that doesn't cause any issues when the searchbar is focused (full width) though.

This would be the perfect solution... if only UNO didn't add that pesky expand sidenav icon 
```css
div[class*="NavBar-container-"]:focus-within div[class*="NavBar-right-"]{
  display: none;
}
```
May need to resort to some JavaScript to fix this one, but I suppose I'll sleep on it for now.

On a different note, we've been looking for someone with a JS background to help out with small scripts. If you're interested feel free to join us over on discord at [Blackberry Themes](https://discord.gg/sfjkDaM).

**Comment by Archmonger** [comment]
Also, I recommend using Github pages links rather than rawcdn (ex. https://archmonger.github.io/Improved-Plex-Mobile-CSS/plex_mobile.js ) and clear your browser's cache each time you want to preview changes.

**Comment by TheGuardianWolf** [comment]
I did some cssing and have settled on a decent solution, let me know what you think. #4 

There are a few !important styles, are these needed? I removed one but it doesn't cause any issues for me. It could be because that I inject the css, so it ends up at the bottom of <head>, and causes it to be parsed last so that it overwrites previous styles.

Switched over to pages so I got the changes immediately, didn't know I could do that. Thanks.

I'll probably look into that project after exam period ends, right now I *should* be quite busy.

**Comment by Archmonger** [comment]
The !important styles are required in order to override inline styles. I only use it when I find it's required.

Also, see: https://github.com/Archmonger/Improved-Plex-Mobile-CSS/pull/4#issuecomment-542399319

**Comment by TheGuardianWolf** [comment]
Would you be able to describe the navbar issues? Is it this?

![img](https://i.imgur.com/sZa7TYE.png)

**Comment by Archmonger** [comment]
Navbar fix has been implemented in `plex_mobile.js`
